In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("train.csv", encoding="latin1")

In [6]:
df.head(3)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62

In [7]:
sales_by_category = df.groupby("Category")["Sales"].sum()
sales_by_category

Category
Furniture          728658.5757
Office Supplies    705422.3340
Technology         827455.8730
Name: Sales, dtype: float64

In [8]:
sales_summary = (
    df.groupby("Category")["Sales"]
    .sum()
    .reset_index()  # Converts Category back to a regular column
    .sort_values(by="Sales", ascending=False)
)

# Format Sales to 2 decimal places
sales_summary["Sales"] = sales_summary["Sales"].round(2)
sales_summary

          Category      Sales
2       Technology  827455.87
0        Furniture  728658.58
1  Office Supplies  705422.33

In [9]:
# Check total sales across Category and Sub-Category
detailed_summary = (
    df.groupby(["Category", "Sub-Category"])[["Sales"]]
    .sum()
    .round(2)
    .reset_index()
)

detailed_summary.head(10)

          Category Sub-Category      Sales
0        Furniture    Bookcases  113813.20
1        Furniture       Chairs  322822.73
2        Furniture  Furnishings   89212.02
3        Furniture       Tables  202810.63
4  Office Supplies   Appliances  104618.40
5  Office Supplies          Art   26705.41
6  Office Supplies      Binders  200028.78
7  Office Supplies    Envelopes   16128.05
8  Office Supplies    Fasteners    3001.96
9  Office Supplies       Labels   12347.73

In [10]:
category_metrics = (
    df.groupby("Category")
    .agg(
        Total_Sales=("Sales", "sum"),
        Order_Count=("Order ID", "nunique"),
        Avg_Order_Value=("Sales", "mean"),
    )
    .round(2)
    .reset_index()
)

category_metrics

          Category  Total_Sales  Order_Count  Avg_Order_Value
0        Furniture    728658.58         1727           350.65
1  Office Supplies    705422.33         3676           119.38
2       Technology    827455.87         1519           456.40